### ISSUE TITLE
Guardians of the Galaxy RT shaders cause segfault during conversion

### ISSUE THREAD

**Issue by pixelcluster** [HansKristian-Work/dxil-spirv#134]
Faulting DXIL: 
[gotg_rt_crash_dxil.zip](https://github.com/HansKristian-Work/dxil-spirv/files/10076674/gotg_rt_crash_dxil.zip)

Backtrace:
```
#0  0x00007ffff7e8adf6 in dxil_spv::CFGNode::dominates (this=0x555555dafff0, other=0x0) at node.cpp:95
#1  0x00007ffff7e631fc in dxil_spv::CFGStructurizer::find_switch_blocks (this=0x7fffffffb5d0, pass=0) at cfg_structurizer.cpp:2056
#2  0x00007ffff7e67318 in dxil_spv::CFGStructurizer::structurize (this=0x7fffffffb5d0, pass=0) at cfg_structurizer.cpp:3067
#3  0x00007ffff7e5c2d8 in dxil_spv::CFGStructurizer::run (this=0x7fffffffb5d0) at cfg_structurizer.cpp:382
#4  0x00007ffff7dfd2cd in dxil_spv_converter_run (converter=0x555555b85ea0) at dxil_spirv_c.cpp:531
#5  0x0000555555582628 in main (argc=2, argv=0x7fffffffdca8) at dxil_spirv.cpp:900
```

**Comment by SingleInfiniteLoop** [comment]
I've got similar crash (I assume) at the very same place when running Battlefield 2042:
```
			auto *dominated_merge_target = find_common_post_dominator_with_ignored_break(node->succ, merge);
			if (node->dominates(dominated_merge_target))
```
I suggest a simple fix like this:
```
			auto *dominated_merge_target = find_common_post_dominator_with_ignored_break(node->succ, merge);
			if (dominated_merge_target && node->dominates(dominated_merge_target))
```
